Mudanças para aceitar http temporariamente e fazer ocr funcionar
digitalse-bomb/back pull request #77
Opened 2021-09-10 09:54 UTC by Matrix2100

2021-09-13 11:59 UTC, raiomarco requested changes

2021-09-13 11:59 UTC, raiomarco commented on pom.xml
> +		<dependency>
Vamos remover isso aqui né

2021-09-13 11:59 UTC, raiomarco commented on src/main/java/com/digitalse/cbm/back/repository/ArquivoRepository.java
> +    @Query("SELECT a.id FROM Arquivo a WHERE a.ocr = true AND a.status = \'Em pre-processamento\' ORDER BY a.criado ASC")
Precisava mesmo de uma query de JPQL aqui?

2021-09-13 11:59 UTC, raiomarco commented on src/main/resources/config/application.yml
> +  rabbitmq:
Me preocupa se isso vai dar erro caso não tenha nada setado no .env

2021-09-13 14:47 UTC, Matrix2100 commented on src/main/java/com/digitalse/cbm/back/repository/ArquivoRepository.java
> +    @Query("SELECT a.id FROM Arquivo a WHERE a.ocr = true AND a.status = \'Em pre-processamento\' ORDER BY a.criado ASC")
sim, mas vou alterar quando der tempo de fazer melhor... criarei uma issue pra isso

2021-09-13 14:49 UTC, Matrix2100 commented on src/main/resources/config/application.yml
> +  rabbitmq:
alterarei a .env.example

2021-09-13 14:49 UTC, Matrix2100 commented on pom.xml
> +		<dependency>
vou comentar porque ainda usaremos o rabbit depois

2021-09-13 14:53 UTC, Matrix2100 commented on src/main/resources/config/application.yml
> +  rabbitmq:
e também já foi comentado na yml

2021-09-14 22:18 UTC, raiomarco approved these changes

2021-09-14 22:20 UTC, merged